### ISSUE TITLE
cannot build on mac with "private: true"

### ISSUE THREAD

**Issue by matzkoh** [azu/gitbook-plugin-github-issue-feedback#8]
```
Error: Cannot copy '/Users/my/repo' to a subdirectory of itself, '/Users/my/repo/_book/gitbook/gitbook-plugin-github-issue-feedback/contents'.
```
this error occur at `gitbook build`.
is there any solutions?

**Comment by azu** [comment]
Can you paste your book.json(GitBook config)? or Can you have reproduce repository?

/cc @yaeda

**Comment by matzkoh** [comment]
Thank you for your quick response.

https://github.com/matzkoh/test-gitbook

I made above repo and can reproduce.

```bash
npm i
npm run build
```

**Comment by yaeda** [comment]
Hi @matzkoh 
Thank you for your report and sample repo. I confirmed your situation.

In the current implementation,  this option doesn't work when the document is in the repository root. I will try to fix in this week. If you are in a hurry, put document to a child directory (like `docs`) and set `root` option in the book.json please.

```
{
  "root": "docs",
  "plugins": [
    "github-issue-feedback"
  ],
  "pluginsConfig": {
    "github-issue-feedback": {
      "repo": "matzkoh/test-gitbook",
      "private": true
    }
  }
}
```

**Comment by matzkoh** [comment]
@yaeda 

Thanks, I understood.

I moved docs into `root` dir and it all works fine now!

Thank you for your reply and awesome feature.
